// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerMonitor.Data;

#nullable disable

namespace ServerMonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServerMonitor.Models.MonitorTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("int");

                    b.Property<string>("ServerLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Targets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Social",
                            IsOnline = false,
                            LastChecked = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "YouTube",
                            ResponseTimeMs = 0,
                            Url = "https://www.youtube.com"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Social",
                            IsOnline = false,
                            LastChecked = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Facebook",
                            ResponseTimeMs = 0,
                            Url = "https://www.facebook.com"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Social",
                            IsOnline = false,
                            LastChecked = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "X",
                            ResponseTimeMs = 0,
                            Url = "https://x.com"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Cloud",
                            IsOnline = false,
                            LastChecked = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AWS",
                            ResponseTimeMs = 0,
                            Url = "https://aws.amazon.com"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Cloud",
                            IsOnline = false,
                            LastChecked = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Azure",
                            ResponseTimeMs = 0,
                            Url = "https://azure.microsoft.com"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Cloud",
                            IsOnline = false,
                            LastChecked = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cloudflare",
                            ResponseTimeMs = 0,
                            Url = "https://www.cloudflare.com"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Government",
                            IsOnline = false,
                            LastChecked = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gov.pl",
                            ResponseTimeMs = 0,
                            Url = "https://www.gov.pl"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
